force-app/main/default/objects/Platform_Setting__c/Platform_Setting__c.object-meta.xml
<CustomObject>
    <label>Platform Setting</label>
    <nameField>
        <displayFormat>PSN - {0000}</displayFormat>
        <label>Platform Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Setting__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Setting__c/fields/LinkedIn_User_ID__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_User_ID__c</fullName>
    <label>LinkedIn User ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Setting__c/fields/Platform_Setting_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Setting_Name__c</fullName>
    <label>Platform Setting Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SocialShareController.cls
public class SocialShareController {
    @AuraEnabled
    public static Map<String, Object> postTextContent(String textMessage, String platformName){
        Map<String,Object> getPostTextContent;
        switch on platformName {
            when 'LinkedIn_Storage' {
                Platform_Setting__c data = [SELECT Id, Name, Access_Token__c, Client_Id__c, Client_Secret__c, Platform_Setting_Name__c, LinkedIn_User_ID__c FROM Platform_Setting__c where Platform_Setting_Name__c = 'LinkedIn_Storage' LIMIT 1];
                
                getPostTextContent = LinkedinService.postContent(data.LinkedIn_User_ID__c, textMessage, data.Access_Token__c);
                system.debug('getPostTextContent' + getPostTextContent);
                
            }
        }
        return getPostTextContent;
    }
    @AuraEnabled
    public static Map<String, Object> postImage (String fileData, String textMessage, String platformName){
        Object obj = JSON.deserializeUntyped(fileData);
        System.debug('file data in postImage======>' + obj);
        
        Map<String, Object> fileDataMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(obj));
        Map<String,Object> postImage;
        String fileBase64 = String.valueOf(fileDataMap.get('base64'));
        system.debug('fileBase64 Line 24 ======>' + fileBase64);
        /*List<String> fileBase = fileBase64.split(',');
String baseFile = fileBase[1]; */
        String baseFile = fileBase64.substringAfter(',');
        //Blob abc = Blob.valueOf(baseFile);
        //system.debug('base file data abc::: ' + abc);
        //system.debug('fileDataMap split full ::: ' + fileBase);
        //system.debug('fileDataMap split ::: ' + fileBase[1]);
        system.debug('base file data ::: ' + baseFile);
        switch on platformName {
            when 'LinkedIn_Storage' {
                Platform_Setting__c data = [SELECT Id, Name, Access_Token__c, Client_Id__c, Client_Secret__c, Platform_Setting_Name__c, LinkedIn_User_ID__c FROM Platform_Setting__c where Platform_Setting_Name__c = 'LinkedIn_Storage' LIMIT 1];
                postImage = LinkedinService.getImageUploadUrl(baseFile , data.LinkedIn_User_ID__c, data.Access_Token__c, textMessage);
                // postImage = LinkedinService.getImageUploadUrl(fileData , data.LinkedIn_User_ID__c, data.Access_Token__c, textMessage);
                system.debug('postImage' + postImage);           
            } 
        }
        return postImage;
    }
}