force-app/main/default/objects/Platform_Setting__c/Platform_Setting__c.object-meta.xml
<CustomObject>
    <label>Platform Setting</label>
    <nameField>
        <displayFormat>PSN - {0000}</displayFormat>
        <label>Platform Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Setting__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Setting__c/fields/Page_Id__c.field-meta.xml
<CustomField>
    <fullName>Page_Id__c</fullName>
    <label>Page Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Setting__c/fields/Platform_Setting_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Setting_Name__c</fullName>
    <label>Platform Setting Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Setting__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Platform_Setting__c/fields/User_Access_Token__c.field-meta.xml
<CustomField>
    <fullName>User_Access_Token__c</fullName>
    <label>User Access Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Storage_OAuth_Configuration__mdt/Storage_OAuth_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Storage OAuth Configuration</label>
    <pluralLabel>Storage OAuth Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Storage_OAuth_Configuration__mdt/fields/OAuth_URL__c.field-meta.xml
<CustomField>
    <fullName>OAuth_URL__c</fullName>
    <label>OAuth URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Storage_OAuth_Configuration__mdt/fields/Page_Token__c.field-meta.xml
<CustomField>
    <fullName>Page_Token__c</fullName>
    <label>Page Token</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Storage_OAuth_Configuration__mdt/fields/Token_URL__c.field-meta.xml
<CustomField>
    <fullName>Token_URL__c</fullName>
    <label>Token URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/FacebookStorageLandingController.cls
public class FacebookStorageLandingController {
     @RemoteAction
	public static Map<String,Object> getAccessToken(String code){
        List<Platform_Setting__c> settings;

        	
        	settings = [SELECT Id, Name, Client_Id__c, Client_Secret__c, Page_Id__c, Access_Token__c, Scope__c, User_Access_Token__c, Platform_Setting_Name__c FROM Platform_Setting__c
                       		where Platform_Setting_Name__c=:PlatformContstants.FACEBOOK_STORAGE_SETTING_NAME LIMIT 1];
        	system.debug('Settings=='+settings);
        if(settings.size() > 0){
            	system.debug('In Settings');
                 List<Storage_OAuth_Configuration__mdt> oAuthConfigs = [
                    SELECT OAuth_URL__c,Page_Token__c,Token_URL__c FROM Storage_OAuth_Configuration__mdt  
                    WHERE DeveloperName = :PlatformContstants.FACEBOOK_STORAGE_SETTING_NAME LIMIT 1
                ];
                HttpRequest req = new HttpRequest();
                req.setEndpoint(oAuthConfigs[0].Token_URL__c);
                req.setMethod('GET');
                req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
                req.setBody('code='+ code +'&client_id='+ settings[0].Client_Id__c +'&client_secret='+ settings[0].Client_Secret__c +'&redirect_uri='+ PlatformSettingsUtil.getRedirectUrls().get(PlatformContstants.FACEBOOK_STORAGE_SETTING_NAME) +'&grant_type=authorization_code');
                //https://graph.facebook.com/v17.0/oauth/access_token?
                //client_id=632457732352283&redirect_uri=https%3A%2F%2Flogin.salesforce.com%2F&client_secret=b8c22aabe1a3c20574c12c6e716ac0dd&
                //code=AQBZU5euMRV0g7ng_ACUgYwbvtNWwfXkaPoDoQBOo-VeXMUPi0Qe8ti6pTtm8FP__1xCXl987Eg1Bh6q4E5j3gHGmllxdKRhkBV5izDrJNziZCShCm2To3jE7I8jqT8j1aXHSFG-0L4jgiVag08fd6m3TCf5m_OTSpIaKHIqFDQtXm_7B1DUxsA0M0f8dJ9yfvFm7DCqfVFsHO3MtIIy0_RqrT3KawEcU5FqPLxbSgyfKeB19EYuHDo8tnm-l5KqeLcWafWoKjCq78If5v-zd7WIci8UjpY3qNUB3QVwcc8kjwx8BCtA85UGly1qHFt4ff2UVMp6W2H4cZlPtdZGQAhS0gKt_kQusFhKGqJu4_qCBW3S-YKdIq41uGS8REdLpfE%23_=_
                Http http = new Http();
                HTTPResponse res = http.send(req);
                system.debug('resNew'+res);
                system.debug('data ==>> ' + res.getBody());
            }
        return new Map<String,Object>{'success' => false, 'message' => 'Unknown Error Occured!'};
    }
}