force-app/main/default/objects/Platform_Setting__c/Platform_Setting__c.object-meta.xml
<CustomObject>
    <label>Platform Setting</label>
    <nameField>
        <displayFormat>PSN - {0000}</displayFormat>
        <label>Platform Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Setting__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <label>Client Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Setting__c/fields/LinkedIn_User_ID__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_User_ID__c</fullName>
    <label>LinkedIn User ID</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Setting__c/fields/Platform_Setting_Name__c.field-meta.xml
<CustomField>
    <fullName>Platform_Setting_Name__c</fullName>
    <label>Platform Setting Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Storage_OAuth_Configuration__mdt/Storage_OAuth_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Storage OAuth Configuration</label>
    <pluralLabel>Storage OAuth Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Storage_OAuth_Configuration__mdt/fields/OAuth_URL__c.field-meta.xml
<CustomField>
    <fullName>OAuth_URL__c</fullName>
    <label>OAuth URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Storage_OAuth_Configuration__mdt/fields/Page_Token__c.field-meta.xml
<CustomField>
    <fullName>Page_Token__c</fullName>
    <label>Page Token</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Storage_OAuth_Configuration__mdt/fields/Token_URL__c.field-meta.xml
<CustomField>
    <fullName>Token_URL__c</fullName>
    <label>Token URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/PlatformController.cls
public class PlatformController {
    @AuraEnabled
    public static String postOnMeta(String textMessage){
        Platform_Setting__c data = [SELECT Id, Name, Access_Token__c, Client_Id__c, Client_Secret__c, Platform_Setting_Name__c, LinkedIn_User_ID__c FROM Platform_Setting__c where Platform_Setting_Name__c = 'LinkedIn_Storage' LIMIT 1];
        List<Storage_OAuth_Configuration__mdt> oAuthConfigs = [
            SELECT OAuth_URL__c,Page_Token__c,Token_URL__c,Base_URL__c FROM Storage_OAuth_Configuration__mdt  
            WHERE DeveloperName = :PlatformContstants.LINKEDIN_STORAGE_SETTING_NAME LIMIT 1
        ];
        String endPoint = oAuthConfigs[0].Base_Url__c + 'v2/ugcPosts';
        System.debug('Endpoint ' + endPoint);
        System.debug('Acccess Token ' + data.Access_Token__c);
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endPoint);
        request.setMethod('POST');
        request.setHeader('Authorization', 'Bearer ' + data.Access_Token__c);
        request.setHeader('Content-Type', 'application/json');
        
        Map<String, Object> requestBodyMap = new Map<String, Object>();
        
        Map<String, Object> specificContentMap = new Map<String, Object>();
        specificContentMap.put('com.linkedin.ugc.ShareContent', new Map<String, Object>{
            'shareCommentary' => new Map<String, Object>{'text' => textMessage},
                'shareMediaCategory' => 'NONE'
                });
        
        Map<String, Object> visibilityMap = new Map<String, Object>{'com.linkedin.ugc.MemberNetworkVisibility' => 'PUBLIC'};
            
            
        requestBodyMap.put('author', 'urn:li:person:'+ String.valueOf(data.LinkedIn_User_ID__c));
        requestBodyMap.put('lifecycleState', 'PUBLISHED');
        requestBodyMap.put('specificContent', specificContentMap);
        requestBodyMap.put('visibility', visibilityMap);
        
        
        String requestBody = JSON.serialize(requestBodyMap);
        
        //System.debug(requestBody); // This will display the JSON string
        
        //request.setHeader('Cookie', 'lidc=\"b=VB69:s=V:r=V:a=V:p=V:g=4123:u=5:x=1:i=1695794940:t=1695806679:v=2:sig=AQHX46hjBWntN6OOJXgWvpFNGjgYWdZT\"; bcookie=\"v=2&f3397cae-a203-4883-8bfd-65ad8f6ec171\'');
        // String bdy ='{"author": "urn:li:person:TYR0aqmL_k", "lifecycleState": "PUBLISHED", "specificContent": { "com.linkedin.ugc.ShareContent": { "shareCommentary": { "text": + '' }, "shareMediaCategory": "NONE" } }, "visibility": { "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC" } }';
        request.setBody(requestBody);
        
        // String body = 'message=' + message;
        // request.setBody(body);
        system.debug('request--.'+request);
        HttpResponse response = http.send(request);
        
        system.debug('response'+response.getBody());
        //refresh();
        //debugAccessToken();
        return response.getBody();
    }
    
   
}